//! Baseline C emitter: one label per basic block, `goto` for every branch.

use std::fmt::Write;

use crate::hir::flat::{FlatFunction, FlatModule, FnSig, Inst, Term, Val};
use crate::hir::op::{BinOp, CastKind, Cmp, FloatCmp, IntCmp};
use crate::hir::ty::Ty;

/// Emit a whole module as one C translation unit.
pub fn emit_module(m: &FlatModule) -> Result<String, String> {
    let mut o = String::new();
    o.push_str("/* generated by lltp (goto baseline) */\n#include <stdint.h>\n\n");
    for d in &m.decls {
        if !d.name.starts_with("llvm.") {
            writeln!(o, "{};", proto(d, None)?).expect("write to String");
        }
    }
    for f in &m.funcs {
        writeln!(o, "{};", proto(&f.sig, None)?).expect("write to String");
    }
    o.push('\n');
    for f in &m.funcs {
        emit_function(f, &mut o).map_err(|e| format!("in `{}`: {e}", f.sig.name))?;
        o.push('\n');
    }
    Ok(o)
}

fn emit_function(f: &FlatFunction, o: &mut String) -> Result<(), String> {
    writeln!(o, "{} {{", proto(&f.sig, Some(&f.param_names))?).expect("write to String");
    for (name, ty) in &f.locals {
        writeln!(o, "    {} {name};", c_ty(ty)?).expect("write to String");
    }
    for b in &f.blocks {
        writeln!(o, "{}:", b.label).expect("write to String");
        for i in &b.insts {
            writeln!(o, "    {}", inst(i)?).expect("write to String");
        }
        writeln!(o, "    {}", term(&b.term)?).expect("write to String");
    }
    writeln!(o, "}}").expect("write to String");
    Ok(())
}

fn proto(s: &FnSig, names: Option<&[String]>) -> Result<String, String> {
    let mut ps: Vec<String> = Vec::new();
    for (i, t) in s.params.iter().enumerate() {
        let ty = c_ty(t)?;
        ps.push(match names {
            Some(n) => format!("{ty} {}", n[i]),
            None => ty,
        });
    }
    if s.variadic {
        ps.push("...".to_string());
    }
    let params = if ps.is_empty() {
        "void".to_string()
    } else {
        ps.join(", ")
    };
    Ok(format!("{} {}({params})", c_ty(&s.ret)?, s.name))
}

pub fn c_ty(t: &Ty) -> Result<String, String> {
    Ok(match t {
        Ty::Void => "void".to_string(),
        Ty::Bool => "_Bool".to_string(),
        Ty::Int(b @ (8 | 16 | 32 | 64), _) => format!("int{b}_t"),
        Ty::Float(32) => "float".to_string(),
        Ty::Float(64) => "double".to_string(),
        Ty::Ptr(_) => "void *".to_string(),
        other => return Err(format!("no C type for {other:?} yet")),
    })
}

fn int_bits(t: &Ty) -> Option<usize> {
    match t {
        Ty::Int(b, _) => Some(*b),
        Ty::Bool => Some(1),
        _ => None,
    }
}

/// Unsigned C type for an integer width (`i1` is carried in a `uint8_t`).
fn uty(bits: Option<usize>) -> Result<&'static str, String> {
    match bits {
        Some(1 | 8) => Ok("uint8_t"),
        Some(16) => Ok("uint16_t"),
        Some(32) => Ok("uint32_t"),
        Some(64) => Ok("uint64_t"),
        other => Err(format!("no unsigned C type for width {other:?}")),
    }
}

fn val(v: &Val) -> Result<String, String> {
    Ok(match v {
        Val::Var(n, _) => n.clone(),
        Val::Addr(n) => format!("(&{n})"),
        Val::Null => "((void *)0)".to_string(),
        Val::Int { value, bits: 1 } => String::from(if *value != 0 { "1" } else { "0" }),
        Val::Int { value, bits } => {
            let t = c_ty(&Ty::Int(*bits, true))?;
            if *value == i64::MIN {
                format!("(({t})(-9223372036854775807LL - 1))")
            } else {
                format!("(({t}){value}LL)")
            }
        }
        Val::Float { value, bits } => {
            if !value.is_finite() {
                return Err("inf/NaN float constants are not supported yet".to_string());
            }
            match bits {
                32 => format!("({value:?}f)"),
                64 => format!("({value:?})"),
                other => return Err(format!("{other}-bit float constants are not supported")),
            }
        }
    })
}

fn inst(i: &Inst) -> Result<String, String> {
    Ok(match i {
        Inst::Load { dest, ptr } => format!("{dest} = {ptr};"),
        Inst::Store { ptr, value } => format!("{ptr} = {};", val(value)?),
        Inst::Copy { dest, src } => format!("{dest} = {};", val(src)?),
        Inst::Bin {
            dest,
            ty,
            op,
            lhs,
            rhs,
        } => format!("{dest} = {};", bin(*op, ty, lhs, rhs)?),
        Inst::Cmp {
            dest,
            pred,
            lhs,
            rhs,
        } => format!("{dest} = {};", cmp(*pred, lhs, rhs)?),
        Inst::Cast {
            dest,
            ty,
            kind,
            src,
        } => format!("{dest} = {};", cast(*kind, ty, src)?),
        Inst::Call { dest, callee, args } => {
            let args = args
                .iter()
                .map(val)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ");
            match dest {
                Some(d) => format!("{d} = {callee}({args});"),
                None => format!("{callee}({args});"),
            }
        }
    })
}

fn bin(op: BinOp, ty: &Ty, l: &Val, r: &Val) -> Result<String, String> {
    let t = c_ty(ty)?;
    let (a, b) = (val(l)?, val(r)?);
    let bits = int_bits(&l.ty());
    let body = match op {
        BinOp::Add | BinOp::FAdd => format!("{a} + {b}"),
        BinOp::Sub | BinOp::FSub => format!("{a} - {b}"),
        BinOp::Mul | BinOp::FMul => format!("{a} * {b}"),
        BinOp::SDiv | BinOp::FDiv => format!("{a} / {b}"),
        BinOp::SRem => format!("{a} % {b}"),
        BinOp::And => format!("{a} & {b}"),
        BinOp::Or => format!("{a} | {b}"),
        BinOp::Xor => format!("{a} ^ {b}"),
        BinOp::AShr => format!("{a} >> {b}"),
        BinOp::UDiv => format!("({u}){a} / ({u}){b}", u = uty(bits)?),
        BinOp::URem => format!("({u}){a} % ({u}){b}", u = uty(bits)?),
        BinOp::LShr => format!("({u}){a} >> {b}", u = uty(bits)?),
        BinOp::Shl => format!("({u}){a} << {b}", u = uty(bits)?),
        BinOp::FRem => return Err("frem needs fmod (math.h); not supported yet".to_string()),
    };
    Ok(format!("({t})({body})"))
}

fn cmp(p: Cmp, l: &Val, r: &Val) -> Result<String, String> {
    let (a, b) = (val(l)?, val(r)?);
    Ok(match p {
        Cmp::Int(ip) => {
            let (op, unsigned) = match ip {
                IntCmp::Eq => ("==", false),
                IntCmp::Ne => ("!=", false),
                IntCmp::Slt => ("<", false),
                IntCmp::Sle => ("<=", false),
                IntCmp::Sgt => (">", false),
                IntCmp::Sge => (">=", false),
                IntCmp::Ult => ("<", true),
                IntCmp::Ule => ("<=", true),
                IntCmp::Ugt => (">", true),
                IntCmp::Uge => (">=", true),
            };
            if unsigned {
                let u = uty(int_bits(&l.ty()))?;
                format!("(({u}){a} {op} ({u}){b})")
            } else {
                format!("({a} {op} {b})")
            }
        }
        Cmp::Float(fp) => match fp {
            FloatCmp::False => "0".to_string(),
            FloatCmp::True => "1".to_string(),
            FloatCmp::Oeq => format!("({a} == {b})"),
            FloatCmp::Ogt => format!("({a} > {b})"),
            FloatCmp::Oge => format!("({a} >= {b})"),
            FloatCmp::Olt => format!("({a} < {b})"),
            FloatCmp::Ole => format!("({a} <= {b})"),
            FloatCmp::Une => format!("({a} != {b})"),
            FloatCmp::One => format!("({a} < {b} || {a} > {b})"),
            FloatCmp::Ord => format!("({a} == {a} && {b} == {b})"),
            FloatCmp::Uno => format!("({a} != {a} || {b} != {b})"),
            FloatCmp::Ueq => format!("!({a} < {b} || {a} > {b})"),
            FloatCmp::Ugt => format!("!({a} <= {b})"),
            FloatCmp::Uge => format!("!({a} < {b})"),
            FloatCmp::Ult => format!("!({a} >= {b})"),
            FloatCmp::Ule => format!("!({a} > {b})"),
        },
    })
}

fn cast(kind: CastKind, ty: &Ty, src: &Val) -> Result<String, String> {
    let t = c_ty(ty)?;
    let s = val(src)?;
    let sbits = int_bits(&src.ty());
    Ok(match kind {
        CastKind::Trunc if matches!(ty, Ty::Bool) => format!("({s} & 1)"),
        CastKind::Trunc | CastKind::SiToFp | CastKind::FpToSi => format!("(({t})({s}))"),
        CastKind::FpExt | CastKind::FpTrunc => format!("(({t})({s}))"),
        CastKind::ZExt | CastKind::UiToFp => format!("(({t})(({}){s}))", uty(sbits)?),
        CastKind::SExt if sbits == Some(1) => format!("(({t})({s} ? -1 : 0))"),
        CastKind::SExt => format!("(({t})({s}))"),
        CastKind::FpToUi => format!("(({t})(({}){s}))", uty(int_bits(ty))?),
    })
}

fn term(t: &Term) -> Result<String, String> {
    Ok(match t {
        Term::Br(l) => format!("goto {l};"),
        Term::CondBr {
            cond,
            then_bb,
            else_bb,
        } => format!("if ({}) goto {then_bb}; else goto {else_bb};", val(cond)?),
        Term::Ret(Some(v)) => format!("return {};", val(v)?),
        Term::Ret(None) => "return;".to_string(),
        Term::Unreachable => "__builtin_unreachable();".to_string(),
    })
}
